name: CVClaims
main: org.cubeville.cvclaims.CVClaims
authors: [FrediW, Ptown16]
version: 1.18
depend: [CVTools, WorldGuard, WorldEdit]

commands:
  claim:
    description: Claim the current WE selection
    permission: cvclaims.claim
    
  claimhere:
    description: Claim a piece of land centered around the player
    permission: cvclaims.claim
    
  subzone:
    description: Create subzones of existing regions
